schema_version: 20180708
name: embracondemo
version: 0.0.38
runtime: node
build_image: fnproject/node:14-dev
run_image: fnproject/node:14
entrypoint: node func.js
triggers:
- name: embracondemo
  type: http
  source: /embracondemo
